### ISSUE TITLE
How to install from source using repeate-thyself?

### ISSUE THREAD

**Issue by timthelion** [polydawn/repeatr#103]
https://github.com/polydawn/repeatr/blob/master/doc/dev/building-repeatr.md#repeating-repeatr doesn't actually say how to extract that generated binary and use it.

**Comment by heavenlyhash** [comment]
heh, heh, excellent point...

Closing this as that particular piece of documentation is temporarily vanishing pending rewriting it for the "r200" version change, but basic glue scripts for extraction is a topic also getting properly touched in the new quickstart guides.
