### ISSUE TITLE
Repeatr fails without modprobe but doesn't need it

### ISSUE THREAD

**Issue by tazjin** [polydawn/repeatr#85]
Basically this:

```
INFO[03-17|13:47:05] Input 3/3 ready 
panic: gosh: command not found: "modprobe" [recovered]
	panic: gosh: command not found: "modprobe" [recovered]
	panic: gosh: command not found: "modprobe"
```

It seems that repeatr attempts to load the AUFS kernel module, but if `modprobe` is present and AUFS isn't it falls back to to "slow fs assembly system" anyways. That fallback should probably also happen if modprobe isn't there.

```
WARN: using slow fs assembly system: install AUFS to use faster systems.
```

**Comment by heavenlyhash** [comment]
Fixed in 4d4cb1e5eb25d3323f3a0a4bd4f73039b221db83 !
