### ISSUE TITLE
cli is now mainatained by urfave

### ISSUE THREAD

**Issue by timthelion** [polydawn/repeatr#92]
"Notice: This is the library formerly known as github.com/codegangsta/cli -- Github will automatically redirect requests to this repository, but we recommend updating your references for clarity."

https://github.com/urfave/cli

But it is imported with the old URL:
https://github.com/polydawn/repeatr/blob/master/cmd/repeatr/main.go#L9

**Comment by heavenlyhash** [comment]
*sigh*.

`sed -r 's#codegangsta#urfave#g'`: 37e10835085bb675312d786ac9fc43644d50bda7
